// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "r6pA5D34dEayELiyWYwVcYo2K8cLFpMdjMcbC69zsqWEag6j3h2ddxFAkQLRw6ZsS3Ek5W";
}
}
}

